version: "3"
services:
  mysql:
    image: mysql
    networks:
      - spring
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=sinch
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    cap_add:
        - SYS_NICE
  api:
    image: com.sinch.gamehighscore/gamehighscore-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/database?autoReconnect=true&useSSL=false
    networks:
      - spring
    ports:
      - "8080:8080"
    depends_on:
      - mysql
networks:
  spring:
    driver: bridge