INSERT INTO category (id, name, image_path) values(1,"Attack", "")
INSERT INTO category (id, name, image_path) values(2,"Defense", "")
INSERT INTO category (id, name, image_path) values(3,"Magic", "")
INSERT INTO category (id, name, image_path) values(4,"Cooking", "")
INSERT INTO category (id, name, image_path) values(5,"Crafting", "")
insert into category (id, name, image_path) values(6,"Overall", "")